name: Publish web-apps/nuxtjs

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths:
      - 'web-apps/nuxtjs/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web-apps/nuxtjs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build nuxtjs supervisor
        run: |
          cd web-apps/nuxtjs/supervisor
          cargo build --release
          cd ../../..

      - name: Docker build and push
        uses: ./.github/workflows/docker-build-and-push
        with:
          registry: ghcr.io
          image-name: leicraftmc/pterodactyl-eggs
          image-tag: nuxtjs
          context: ./web-apps/nuxtjs
          username: ${{ github.actor }}
          gh-token: ${{ secrets.PAT  }}

